### ISSUE TITLE
Query related to the dataset

### ISSUE THREAD

**Issue by utpal150894** [BigDataWUR/ML4ClimateAdaptationPolicy#4]
Sir,can you please provide the entire processed data set using which you build your model.
Because when I run the  sqlite_db.py   script under python script section a  climate.db file  generated,which contains 13,895 labeled block data and only 324 unlabeled data.whether this is the only processed data using which you built your model.

I need your help.Even the scrapper script isn't working and also I am confused about from where I could scrap all the uk policy data.Because the site you providing seems like its not a single site from which I could scrap the data.

Currently I am working in a similar topic,so if possible please help.if possible please provide the complete prepossed dataset using which you build this model,so that it could be easy for me to verify the accuracy of this model.

**Comment by ionathan** [comment]
As stated in the README file, and the paper the full dataset is available here: https://doi.org/10.5281/zenodo.3911168
